# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "application.fullname" . }}-consoleapi
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    component: "consoleapi"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "application.name" . }}
    helm.sh/chart: {{ template "application.chart" . }}
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "application.name" . }}
      component: "consoleapi"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "application.name" . }}
        ocm-antiaffinity-selector: "consoleapi"
        component: "consoleapi"
        release: {{ .Release.Name }}
        chart: {{ template "application.chart" . }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ template "application.name" . }}
        helm.sh/chart: {{ template "application.chart" . }}
      annotations:
        productName: "Open Cluster Management - Server"
        productVersion: "2.0.0"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ template "application.fullname" . }}
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.arch }}
                - {{ . }}
                {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - consoleapi
                - key: component
                  operator: In
                  values:
                  - consoleapi
          - weight: 35
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - consoleapi
                - key: component
                  operator: In
                  values:
                  - consoleapi
      {{- with .Values.hubconfig.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: hcm-ui-api
        image: {{ .Values.global.imageOverrides.console_api }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        resources:
        {{- toYaml .Values.consoleapi.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        env:
        {{- if .Values.hubconfig.proxyConfigs }}
        - name: HTTP_PROXY
          value: {{ .Values.hubconfig.proxyConfigs.HTTP_PROXY }}
        - name: HTTPS_PROXY
          value: {{ .Values.hubconfig.proxyConfigs.HTTPS_PROXY }}
        - name: NO_PROXY
          value: {{ .Values.hubconfig.proxyConfigs.NO_PROXY }}
        {{- end }}
        ports:
        - containerPort: 4000
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livenessProbe
            port: 4000
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readinessProbe
            port: 4000
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: uiapi-certs
          mountPath: /opt/app-root/console-api/sslcert
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}
      volumes:
      - name: uiapi-certs
        secret:
          secretName: {{ template "application.fullname" . }}-uiapi-certs
          items:
          - key: tls.crt
            path: consoleapi.crt
          - key: tls.key
            path: consoleapi.key
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
